### PR TITLE
Implementing a visualization feature for tracking budget performance …

### PR DESCRIPTION
**Pull request by Blindspot22**
Implementing a visualization feature for tracking budget performance

### CODE REVIEW

**Comment by AssahBismarkabah** [comment]
hello @Blindspot22  great job
but do you have a demo of the `visualization` feature for tracking budget performance?

**Review by Awambeng — APPROVED** [review]
Good job @Blindspot22 clean job

**Review by AssahBismarkabah — CHANGES_REQUESTED** [review]
hello @Blindspot22 great job
but do you have a demo of the `visualization` feature for tracking budget performance?

**Comment by Blindspot22** [comment]
@AssahBismarkabah Man things are not showing on my side

**Review by Blindspot22 — COMMENTED** [review]
good

**Pull request merged**
